import React, { useState } from 'react';
import { X, FolderOpen, FileText, Image, Download, Eye } from 'lucide-react';
import FileViewer from './FileViewer';
import { motion, AnimatePresence } from 'framer-motion';

export default function WorkspaceFiles({ isOpen, onClose, files = [] }) {
  const [selectedFileToView, setSelectedFileToView] = useState(null);
  const getFileIcon = (type, name) => {
    if (type?.startsWith('image/') || name.match(/\.(jpg|jpeg|png|gif)$/i)) return <Image className="w-5 h-5 text-blue-400" />;
    return <FileText className="w-5 h-5 text-white/90" />;
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 bg-black/40 backdrop-blur-sm">
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="w-full max-w-4xl max-h-full bg-white dark:bg-[#0c0c0e] rounded-2xl shadow-2xl flex flex-col overflow-hidden border border-zinc-200 dark:border-zinc-800"
          >
            {/* Header */}
            <header className="sticky top-0 z-10 bg-white dark:bg-[#0c0c0e] border-b border-zinc-200 dark:border-zinc-800 shrink-0">
              <div className="px-6 h-16 flex items-center justify-between">
                <div className="flex items-center gap-2.5 text-zinc-900 dark:text-white">
                  <FolderOpen className="w-5 h-5 text-purple-500" />
                  <h1 className="text-lg font-semibold tracking-tight">Workspace Files</h1>
                </div>
                <button
                  onClick={onClose}
                  className="p-2 -mr-2 rounded-lg text-zinc-500 hover:text-zinc-900 hover:bg-zinc-100 dark:text-zinc-400 dark:hover:text-white dark:hover:bg-zinc-800 transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </header>

            {/* Main Content */}
            <div className="flex-1 overflow-y-auto w-full p-6 sm:p-8 custom-scrollbar">
              <div className="mb-8">
                <h2 className="text-2xl font-bold tracking-tight mb-2">Files & Artifacts</h2>
                <p className="text-zinc-500 dark:text-zinc-400 max-w-2xl text-[15px] leading-relaxed">
                  View and download files generated by the agent during all the sessions.
                </p>
              </div>

              {files.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-16 text-center">
                  <div className="w-16 h-16 rounded-full bg-zinc-100 dark:bg-zinc-800/50 flex items-center justify-center mb-4">
                    <FileText className="w-8 h-8 text-zinc-400" />
                  </div>
                  <h3 className="text-lg font-semibold mb-1">No files yet</h3>
                  <p className="text-zinc-500 dark:text-zinc-400">Files attached to chat or generated by agents will appear here.</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {files.map((file, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.4, delay: index * 0.05 }}
                      className="group flex flex-col p-4 bg-zinc-50 dark:bg-[#151515] rounded-2xl border border-zinc-200 dark:border-zinc-800/80 hover:border-purple-500/30 transition-colors"
                    >
                      <div className="flex items-start justify-between mb-4">
                        <div className="w-12 h-12 rounded-xl bg-white dark:bg-white/5 flex items-center justify-center shadow-sm border border-black/5 dark:border-white/10">
                          {getFileIcon(file.type, file.name)}
                        </div>
                        <div className="flex gap-1">
                          <button
                            className="p-1.5 rounded-lg text-zinc-400 hover:text-zinc-900 hover:bg-white dark:hover:text-white dark:hover:bg-zinc-700 transition-colors"
                            onClick={() => {
                              if (file.url || file.rawFile) {
                                const url = file.url || URL.createObjectURL(file.rawFile);
                                const a = document.createElement('a');
                                a.href = url;
                                a.download = file.name;
                                document.body.appendChild(a);
                                a.click();
                                document.body.removeChild(a);
                                if (!file.url) URL.revokeObjectURL(url);
                              }
                            }}
                            title="Download"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                          <button
                            className="p-1.5 rounded-lg text-zinc-400 hover:text-zinc-900 hover:bg-white dark:hover:text-white dark:hover:bg-zinc-700 transition-colors"
                            onClick={() => setSelectedFileToView(file)}
                            title="View"
                          >
                            <Eye className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                      <div className="flex flex-col">
                        <span className="font-semibold text-[14px] text-zinc-900 dark:text-white truncate" title={file.name}>{file.name}</span>
                        <div className="flex items-center justify-between mt-1">
                          <span className="text-[12px] text-zinc-500 dark:text-zinc-400">{file.sizeFormatted}</span>
                          <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium ${file.source === 'agent' ? 'bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300' : 'bg-zinc-200 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300'}`}>
                            {file.source === 'agent' ? 'Generated' : 'Uploaded'}
                          </span>
                        </div>
                      </div>
                    </motion.div>
                  ))}
                </div>
              )}
            </div>
          </motion.div>
        </div>
      )}
      <FileViewer
        file={selectedFileToView}
        onClose={() => setSelectedFileToView(null)}
      />
    </AnimatePresence>
  );
}
